name: Merge hotfix to develop

on:
  push:
    branches:
      - develop

permissions:
  contents: write
 

jobs:
  merge-hotfix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
          
      - name: Set up Git
        run: |
          git config --global user.email "${{ env.GIT_USER_EMAIL }}"
          git config --global user.name "${{ env.GIT_USER_NAME }}"

      - name: Fetch all branches and tags
        run: git fetch --prune

      - name: Merge hotfix
        run: |
          git checkout -B hotfix origin/hotfix
          git pull origin hotfix
          git checkout develop
          git merge --no-ff --no-edit --allow-unrelated-histories hotfix
          git push origin develop
