name: Merge hotfix to develop

on:
  push:
    branches:
      - develop

jobs:
  merge-hotfix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Merge hotfix
        run: |
          git fetch --all
          git checkout -B hotfix origin/hotfix
          git pull origin hotfix
          git checkout develop
          git merge --no-ff --no-edit --allow-unrelated-histories hotfix
          git push origin develop
