name: Merge hotfix to develop

on:
  push:
    branches:
      - develop

env:
  GIT_USER_EMAIL: renansouza.oliv@outlook.com
  GIT_USER_NAME: renansouzzzz

permissions:
  contents: write

jobs:
  merge-hotfix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "${{ env.GIT_USER_EMAIL }}"
          git config --global user.name "${{ env.GIT_USER_NAME }}"

      - name: Merge hotfix
        run: |
          git fetch --all
          git switch hotfix
          git pull origin hotfix
          git checkout develop
          git merge --no-edit --allow-unrelated-histories hotfix
          git push develop
